### ISSUE TITLE
Alert - action not defined

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#110]
אם לוחצים על כפתור התחלה אבל לא הגדירו פעולה אז להוסיף הודעה

יש להגדיר את פעולות האוכלוסייה לפני ההפעלה

@Ron-Teller

**Comment by Ron-Teller** [comment]
זה מונע להגדיר אוכלוסיה שלא זזה, כמו במודל של הפיזיקה שדוד יצר

**Comment by Asnat-Zohar** [comment]
הבנתי, זה בסדר גמור, רק ביקשתי להוסיף הודעה : יש להגדיר את פעולות האוכלוסייה לפני ההפעלה

@Ron-Teller
