### ISSUE TITLE
Pencil is stucked after alert

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#111]
After the alert of no properties something does not work properly. Do the following:
1. Add balls without properties
2. Click OK in the alert message
3. The pencil is left inside the window, **it should disappear**
![image](https://user-images.githubusercontent.com/78302632/124144365-908b5f00-da94-11eb-8261-a0018455c390.png)

4. Click button "Add balls", the balls are added immediatly without clicking the pencil, see the green balls outside the wall

![image](https://user-images.githubusercontent.com/78302632/124144441-a39e2f00-da94-11eb-8c5b-3356edb6b3e1.png)

@Ron-Teller

**Comment by Ron-Teller** [comment]
Unable to reproduce bug (steps 3 and 4 did not happen), could you please try to reproduce it and document steps? What was the state of the model before running steps 1-4?

**Comment by Asnat-Zohar** [comment]
Now it is OK
