### ISSUE TITLE
After Halo - pencil not updated

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#121]
After clicking halo, can't add balls, the pencil is still with the square of the halo. Only if you click twice with the pencil you can add balls

![image](https://user-images.githubusercontent.com/78302632/125424958-2189f716-2519-416b-9b68-859abc54d59d.png)

@Ron-Teller

**Comment by Ron-Teller** [comment]
Can not reproduce the bug, everything works for me
