### ISSUE TITLE
Marks are not updated

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#122]
In general - the marks are not updated, not erased with the first click.

Trace is more problematic. Trace after halo: 
Selecting trace after having a halo and remove the halo - can't draw trace

![image](https://user-images.githubusercontent.com/78302632/125425334-4563a789-3474-409e-9b32-68f170c7305a.png)

@Ron-Teller

**Comment by Ron-Teller** [comment]
Can not reproduce the bug, could you please try reproducing the bug, or writing the exact steps?
