### ISSUE TITLE
Visualization of collide to react

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#124]
Visualize any collision by flashing molcules
Visualize effective collision by a different flashing

Create a widget to enable/disable flashing

@Ron-Teller

**Comment by Asnat-Zohar** [comment]
שרונה מציעה להוסיף בלוק של התנגשות כדי לראות שינוי כיוון
בנוסף מציעה להוסיף סימונים למתים/נולדים כמו בטורף נטרף
העלתה גם הצעה לסמן התנגשויות ותגובות (כדי להראות שלא כל התנגשות היא פורייה)
@Ron-Teller

**Comment by sharonatlevy** [comment]
היי

יש כבר בלוק של התנגשות - (שינוי כיוון ומהירות לפי כללי התנגשות) - אולי אני שוכחת משהו?

**Comment by Asnat-Zohar** [comment]
לא רואה...?
