### ISSUE TITLE
Group 1 dies faster

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#125]
It looks as the caculation is not the same for the two groups.
For the same conditions
![image](https://user-images.githubusercontent.com/78302632/126034360-52889e58-2fdc-45e5-8e70-3b0567e4d456.png)

group 1 dies faster
![image](https://user-images.githubusercontent.com/78302632/126034373-3e591b27-73a6-4626-ac8b-72992022b1e5.png)
 
at the end, only group 2 is left (at any initial concitions)
![image](https://user-images.githubusercontent.com/78302632/126034404-723a0d37-29b0-41dc-9465-1aa92aa78e77.png)

More: Looks like balls from group 2 almost not removed. Even when I tried the following, only group 1 dies:
![image](https://user-images.githubusercontent.com/78302632/126061404-58afc10b-5eee-4b2b-955e-f85b52fed662.png)

@Ron-Teller

**Comment by Asnat-Zohar** [comment]
Ron will enable ordering of removing and than adding a ball

**Comment by Asnat-Zohar** [comment]
Even now, group 1 dies much quicker.
For initial conditions:
![image](https://user-images.githubusercontent.com/78302632/126452998-6aca53ec-e302-4f99-8f15-5d85be53c460.png)

After few steps:
![image](https://user-images.githubusercontent.com/78302632/126453186-46ff14af-d080-415a-9d8e-4aeff87d577a.png)

**Comment by Asnat-Zohar** [comment]
עדיין לא מאוזן, אחת האוכלוסיות יורדת הרבה יותר מהר מהשניה

**Comment by Ron-Teller** [comment]
Seems to work fine, the thing is that eventually one of the populations will get "luckier" combinatorically and get more balls added to it than the other, and it will tip the balance and will eventually remove the other population.
