### ISSUE TITLE
Collisions' hallo disappear

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#143]
Do the following:
1. Run with show-collisions
2. Stop
3. Select "Trace"
4. Click button ציור סמן
5. The collisions' hallo disappear

![image](https://user-images.githubusercontent.com/78302632/127276530-97408170-5bda-46f1-be1a-25bce3ac54b1.png)
![image](https://user-images.githubusercontent.com/78302632/127276595-0e02969c-ef85-4e3d-bd95-0c6d561911f9.png)

**Comment by Ron-Teller** [comment]
The animations don't disappear actually, it is that if the "ציור סמן" button is pressed down then animations in the world keep running. The animations will be changed so that they will paused if the model is not running.
