### ISSUE TITLE
Halo, trace, and counter

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#40]
Few issues:
1. Can we have any feedback that a specific ball will be traced or have a halo? currently you can't know if you succeeded.
2. Currently you can't remove the halo/trace/counter. Can the button stays selected when it shows the halo/trace/counter but when you deselect it the halo/trace/counter will disappear?
3. If user press remove buttons then remove also the trace. Currently, they are left in place
![image](https://user-images.githubusercontent.com/78302632/109412187-3a57c380-79af-11eb-841b-f56dd18072a1.png)

@Ron-Teller

**Comment by Ron-Teller** [comment]
**1. Can we have any feedback that a specific ball will be traced or have a halo? currently you can't know if you succeeded.**
For halo the feedback is that a halo is created. In the next update the halo's will be yellow and more noticeable.
For tracing, need to think of a way to visualize that a ball has been successfully traced.

**2. Currently you can't remove the halo/trace/counter. Can the button stays selected when it shows the halo/trace/counter but when you deselect it the halo/trace/counter will disappear?**
It is possible to remove halo/trace/counter, by pressing the "מחיקה" button. 
The brush will be set to remove what it was last drawing. 
Now you can click on any ball to remove its halo, make it stop tracing (won't remove the trace it has drawn so far in the world), or remove a counter.

**3. If user press remove buttons then remove also the trace. Currently, they are left in place**
Maybe we should make a separate button for this. Also, it is not possible to remove a trace drawn by a single ball. It is only possible to remove all traces drawn by all balls.

**Comment by Asnat-Zohar** [comment]
After discussion on 3.3.21:

1. Feedback - for the halo have a circle **only**. Currently, if the "if ball meets" condition is active the halo is a triangular.
2. Feedback - for the trace make the ball flash.
3. Remove trace - When user press on "remove balls" - remove also **all the trace**.
