### ISSUE TITLE
Add button "remove marks"

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#45]
להוסיף כפתור מחיקה לסמנים.
הכפתור ישנה את הסמן בהתאם לתוכן שהוא מוחק (הפעולה האחרונה).
 בלחיצה על הכפתורים האחרים, הסמן ישתנה בהתאם.
 במחיקה יהיה אותו ציור של הסמן אבל באפור.

@Ron-Teller

**Comment by Ron-Teller** [comment]
Issue #49 took care of this issue
