### ISSUE TITLE
Design 1 - buttons and sliders

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#57]
1. Decrease size of "model speed" slider - No, impossible
2. Change the green backgroupnd of the sliders to darker green - No, impossible
![image](https://user-images.githubusercontent.com/78302632/110804688-12a70c00-8289-11eb-937f-7d566e8c3a57.png)
3. Insert the titles into the monitors titles 
![image](https://user-images.githubusercontent.com/78302632/110804876-3ec28d00-8289-11eb-9510-aca2a9e4fa35.png)
4. Insert title into the buttons 
![image](https://user-images.githubusercontent.com/78302632/110804964-5863d480-8289-11eb-8b35-073fc11bf254.png)
5. Remove the word "מספר" from the slider, should be look as: 
![image](https://user-images.githubusercontent.com/78302632/110805346-aa0c5f00-8289-11eb-9688-6df9905526cd.png)

@Ron-Teller

**Comment by Ron-Teller** [comment]
![image](https://user-images.githubusercontent.com/12688282/111882821-4cca8900-89c0-11eb-9228-e7ec664b7c61.png)

Not possible to have 2 lines in monitor title, it is only possible to have 1 line such as:
![image](https://user-images.githubusercontent.com/12688282/111882870-974c0580-89c0-11eb-9573-d93e5ac9618a.png)

It is possible to have a combination of a monitor and note above it:
![image](https://user-images.githubusercontent.com/12688282/111882936-06c1f500-89c1-11eb-9868-9c0281efb9be.png)
