### ISSUE TITLE
Save file as

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#65]
בשמירת קובץ צריך להוסיף את הסיומת html אחרת לא נפתח, תלמיד לא יודע לעשות את זה

When Save file, add the option of html, otherwise students don't know how to save it

@Ron-Teller

**Comment by Ron-Teller** [comment]
The file is not an html file but a .nlogo file, you can not open it with a browser, only by using "טעינת מודל".
![image](https://user-images.githubusercontent.com/12688282/112393249-73136000-8d03-11eb-9d72-4cfd7c1eec47.png)

 It does not save the block state either (of nettango). There is currently no feature in the language to enable us to do this. It only saves the state of the netlogo world.

**Comment by Asnat-Zohar** [comment]
Add a ".nlogo" to file name
@Ron-Teller
