### ISSUE TITLE
Add speed lable

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#69]
Under the marks menu, add speed lable. It should be with the halo, as additioal mark (not instead). 
Need to have "halo" (only), and "halo with speed"

ask turtle * [ set label *speed of turtle* ]
set label-color

Hebrew: הילה עם מהירות

"בנוסף לשנות את "מעקב אחרי כדור" ל"עקבות של כדור

@Ron-Teller

**Comment by Asnat-Zohar** [comment]
בצבע של המהירות צריך להיות בצבע הקיר כדי שיראו. כרגע הוא לבן ואם הרקע גם לבן אז לא רואים אותו. אם אפשר, גם ההילה צריכה להיות באותו הצבע, עכשיו היא בצהוב אבל אם הרקע יהיה צהוב אז לא יראו אותה. למטה תמונה עם סימון מהירות לבן ורקע לבן

![image](https://user-images.githubusercontent.com/78302632/112611314-b8807c00-8e2e-11eb-9502-5035371526fe.png)

@Ron-Teller

**Comment by Ron-Teller** [comment]
Fixed by issues #73 #74
