### ISSUE TITLE
Remove mark not always works

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#71]
. המחיקה לא תמיד עובדת, אני לא ממש מצליחה לשחזר בדיוק. הפעולות שאני עושה הן לשים סמן, להריץ, למחוק, לשנות סמן, להריץ, למחוק את הסמן. ברוב המקרים המחיקה לא עובדת.
@Ron-Teller

**Comment by Ron-Teller** [comment]
Closing this issue since I need exact steps to reproduce the bug
