### ISSUE TITLE
Marks - draw button doesn't work 

### ISSUE THREAD

**Issue by Asnat-Zohar** [Systems-Learning-and-Development-Lab/MMM#82]
There is a confusion/redandunce  between what the menu "without mark" does and the button "remove mark" does.

Steps that I do:
1. Draw a Halo (without lable) by pressing button "Draw" and clicking on a ball
2. Menu --> No mark --> OK, the halo was removed.
3. Menu --> Halo --> **immediatly** draws a halo, without using the button. I can't select the ball.
4. Menu --> Trace --> **change** the Halo to Trace (I guee on the same ball)
5. This happens also if I use the remove button instead of the menu.
6. Button Remove mark works.
7. This is true for all marks, **except** for the Counter. The counter cannot be removed by using the menu either the button.
![image](https://user-images.githubusercontent.com/78302632/115136951-d4410180-a02b-11eb-80a0-0621422e0b07.png)

@Ron-Teller

**Comment by Ron-Teller** [comment]
Fixed in latest commits
